#!/usr/bin/env python3
"""Tests for scripts/tw_board.py — the researched Territory War board.

The board it replaced was generated by faction-tag affinity and shipped lineups like
"Ugnaught / General Syndulla / Kuiil / Darth Sidious / Poe Dameron", left four Galactic
Legends with no TW squad at all, and double-booked units between the wall and the bank.
None of that is a solver bug — the board is now DATA, so what has to be defended is the
set of properties that make the data fieldable. Every check below corresponds to a way
the previous board was actually wrong.
"""
import json
import os
import sys

import pytest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "scripts"))

import tw_board as tb                 # noqa: E402


OWN = {
    "LEADA":  {"b": "LEADA", "n": "Lead A", "ct": 1, "g": 13, "rt": 9, "r": 7, "gp": 30000},
    "ALLY1":  {"b": "ALLY1", "n": "Ally One", "ct": 1, "g": 13, "rt": 9, "r": 7, "gp": 25000},
    "ALLY2":  {"b": "ALLY2", "n": "Ally Two", "ct": 1, "g": 13, "rt": 9, "r": 7, "gp": 25000},
    "ALLY3":  {"b": "ALLY3", "n": "Ally Three", "ct": 1, "g": 13, "rt": 9, "r": 7, "gp": 25000},
    "ALLY4":  {"b": "ALLY4", "n": "Ally Four", "ct": 1, "g": 13, "rt": 9, "r": 7, "gp": 25000},
    "ALLY5":  {"b": "ALLY5", "n": "Ally Five", "ct": 1, "g": 13, "rt": 9, "r": 7, "gp": 25000},
    "LOWGEAR": {"b": "LOWGEAR", "n": "Low Gear", "ct": 1, "g": 11, "rt": 2, "r": 7, "gp": 9000},
    "SHIPA":  {"b": "SHIPA", "n": "Ship A", "ct": 2, "g": 1, "rt": 2, "r": 7, "gp": 40000},
}


def squad(sid, units, band="FRONT", name="Squad"):
    return {"id": sid, "name": name, "hu_name": f"TW {sid} {name}",
            "band": band, "units": units, "why": "because"}


def board(defense=(), offense=(), fleets=None):
    return {"defense": list(defense), "offense": list(offense),
            "fleets": fleets or {"defense": [], "offense": []}}


def errors_for(b):
    return tb.validate(b, OWN)[0]


# --- the properties that make a board fieldable -------------------------------

def test_a_clean_board_validates():
    b = board([squad("D01", ["LEADA", "ALLY1", "ALLY2", "ALLY3", "ALLY4"])])
    errs, warns, used = tb.validate(b, OWN)
    assert errs == []
    assert warns == []
    assert set(used) == {"LEADA", "ALLY1", "ALLY2", "ALLY3", "ALLY4"}


def test_a_unit_may_not_appear_on_two_squads():
    """A unit set on TW defense cannot attack and cannot be set again. The old wall
    double-booked units between the graded bank and the tier-2 wall."""
    b = board([squad("D01", ["LEADA", "ALLY1", "ALLY2", "ALLY3", "ALLY4"]),
               squad("D02", ["ALLY1", "ALLY5", "LOWGEAR", "SHIPA", "LEADA"], band="MID")])
    errs = errors_for(b)
    assert any("ALLY1" in e and "already used" in e for e in errs)
    assert any("LEADA" in e and "already used" in e for e in errs)


def test_defense_and_offense_share_no_unit():
    b = board([squad("D01", ["LEADA", "ALLY1", "ALLY2", "ALLY3", "ALLY4"])],
              [{"id": "O01", "name": "Att", "hu_name": "TW O01 Att",
                "units": ["LEADA", "ALLY5"], "size": 2, "for": "x"}])
    assert any("already used" in e for e in errors_for(b))


def test_unowned_unit_is_an_error_not_a_silent_drop():
    b = board([squad("D01", ["LEADA", "ALLY1", "ALLY2", "ALLY3", "NOSUCHUNIT"])])
    assert any("NOSUCHUNIT" in e and "NOT OWNED" in e for e in errors_for(b))


def test_a_ship_cannot_be_a_character_squad_member():
    b = board([squad("D01", ["LEADA", "ALLY1", "ALLY2", "ALLY3", "SHIPA"])])
    assert any("SHIPA" in e and "ship" in e for e in errors_for(b))


def test_wrong_size_is_an_error():
    b = board([squad("D01", ["LEADA", "ALLY1", "ALLY2"])])
    assert any("3 units" in e for e in errors_for(b))


def test_a_short_offense_squad_is_legal_when_it_declares_its_size():
    """TW pays the attacker +1 per empty slot, so a 2-unit clear is a real play."""
    b = board(offense=[{"id": "O01", "name": "Bane", "hu_name": "TW O01 Bane",
                        "units": ["LEADA", "ALLY1"], "size": 2, "for": "solo"}])
    assert errors_for(b) == []


def test_low_gear_warns_but_does_not_block():
    b = board([squad("D01", ["LEADA", "ALLY1", "ALLY2", "ALLY3", "LOWGEAR"])])
    errs, warns, _ = tb.validate(b, OWN)
    assert errs == []
    assert any("Low Gear" in w for w in warns)


def test_bands_must_be_real_and_ordered_front_to_back():
    """The file IS the placement order — a MID row above a FRONT row means the sheet
    tells you to put a weaker wall in the scarcer slot, which is the 2026-08-11 mistake."""
    good = board([squad("D01", ["LEADA", "ALLY1", "ALLY2", "ALLY3", "ALLY4"], "FRONT"),
                  squad("D02", ["ALLY5", "LOWGEAR", "SHIPA", "LEADA", "ALLY1"], "BACK")])
    assert not any("band order" in e for e in errors_for(good))

    bad = board([squad("D01", ["LEADA", "ALLY1", "ALLY2", "ALLY3", "ALLY4"], "BACK"),
                 squad("D02", ["ALLY5", "LOWGEAR", "SHIPA", "LEADA", "ALLY1"], "FRONT")])
    assert any("band order" in e for e in errors_for(bad))

    nonsense = board([squad("D01", ["LEADA", "ALLY1", "ALLY2", "ALLY3", "ALLY4"], "MIDDLE")])
    assert any("band" in e and "MIDDLE" in e for e in errors_for(nonsense))


def test_duplicate_squad_ids_are_caught():
    b = board([squad("D01", ["LEADA", "ALLY1", "ALLY2", "ALLY3", "ALLY4"]),
               squad("D01", ["ALLY5", "LOWGEAR", "SHIPA", "LEADA", "ALLY1"], band="MID")])
    assert any("duplicate squad id" in e for e in errors_for(b))


def test_a_fleet_may_not_contain_a_character():
    b = board(fleets={"defense": [{"id": "F1", "name": "F", "hu_name": "TW F1",
                                   "units": ["SHIPA", "LEADA"]}], "offense": []})
    assert any("LEADA" in e and "character" in e for e in errors_for(b))


# --- the emitted artefacts -----------------------------------------------------

def test_payload_matches_what_upload_hotutils_expects():
    b = board([squad("D01", ["LEADA", "ALLY1", "ALLY2", "ALLY3", "ALLY4"])],
              [{"id": "O01", "name": "Att", "hu_name": "TW O01 Att",
                "units": ["ALLY5"], "size": 1, "for": "x"}],
              {"defense": [{"id": "F1", "name": "Fleet", "hu_name": "TW F1 Fleet",
                            "units": ["SHIPA"]}], "offense": []})
    for d in tb.payload(b, OWN):
        assert set(d) == {"n", "sz", "ct", "cat", "u"}
        assert d["sz"] == len(d["u"])
        assert d["ct"] in (1, 2)
        assert d["cat"].startswith("TW "), "the scoped upload keys off this prefix"
        for pair in d["u"]:
            assert len(pair) == 2 and all(isinstance(x, str) for x in pair)
    cats = {d["cat"] for d in tb.payload(b, OWN)}
    assert cats == {"TW - Def FRONT", "TW - Offense", "TW Fleet - Defense"}


def test_defense_categories_carry_the_band_so_the_tabs_match_the_map():
    """One 50-row defence tab cannot tell you where to stop placing. The band IS the
    instruction, so it has to survive into the category the player filters on."""
    b = board([squad("F01", ["LEADA", "ALLY1", "ALLY2", "ALLY3", "ALLY4"], "FRONT"),
               squad("B01", ["ALLY5", "LOWGEAR", "SHIPA", "LEADA", "ALLY1"], "BACK")])
    cats = {d["n"]: d["cat"] for d in tb.payload(b, OWN)}
    assert cats["TW F01 Squad"] == "TW - Def FRONT"
    assert cats["TW B01 Squad"] == "TW - Def BACK"


def test_placement_sheet_lists_bands_front_first_and_names_the_offense_holdback():
    b = board([squad("D01", ["LEADA", "ALLY1", "ALLY2", "ALLY3", "ALLY4"], "FRONT"),
               squad("D02", ["ALLY5", "LOWGEAR", "SHIPA", "LEADA", "ALLY1"], "BACK")],
              [{"id": "O01", "name": "Att", "hu_name": "TW O01 Att",
                "units": ["ALLY5"], "size": 1, "for": "clears the Rey wall"}])
    text = tb.sheet(b, OWN)
    assert text.index("===== FRONT =====") < text.index("===== BACK =====")
    assert "HELD BACK FOR OFFENSE" in text
    assert "clears the Rey wall" in text


# --- the board actually shipped ------------------------------------------------

@pytest.mark.skipif(not os.path.exists(tb.BOARD_FILE), reason="board not built yet")
def test_the_shipped_board_is_fieldable_against_the_live_roster():
    b = json.load(open(tb.BOARD_FILE))
    own, _ = tb.load_roster()
    errs, _warns, _used = tb.validate(b, own)
    assert errs == [], "\n".join(errs)


@pytest.mark.skipif(not os.path.exists(tb.BOARD_FILE), reason="board not built yet")
def test_every_galactic_legend_has_a_territory_war_squad():
    """The complaint that triggered this rebuild: four GLs — JMK, JML, Jabba and GL
    Ahsoka — were on no TW squad at all, so 20 of the account's best units sat idle
    while filler banked the same +30."""
    b = json.load(open(tb.BOARD_FILE))
    own, _ = tb.load_roster()
    placed = set(tb.validate(b, own)[2])
    gls = {"JABBATHEHUTT", "GLREY", "GLLEIA", "GLAHSOKATANO", "JEDIMASTERKENOBI",
           "SUPREMELEADERKYLOREN", "SITHPALPATINE", "LORDVADER", "GRANDMASTERLUKE"}
    assert gls <= placed, f"GLs with no TW squad: {sorted(gls - placed)}"


@pytest.mark.skipif(not os.path.exists(tb.BOARD_FILE), reason="board not built yet")
def test_every_squad_records_why_it_is_there():
    """A board nobody can audit is the one that drifts back into faction-tag filler."""
    b = json.load(open(tb.BOARD_FILE))
    for s in b.get("defense", []):
        assert s.get("why"), f"{s.get('id')} has no rationale"
    for s in b.get("offense", []):
        assert s.get("for"), f"{s.get('id')} does not say what it attacks"
